version: '3.8'
services:
  db:
    # DockerHubにあるmysql8.0のイメージを使用
    image: mysql:8.0.32
    # MySQL8.0以降の認証方式に元に戻す設定
    command: --default-authentication-plugin=mysql_native_password
    # dbディレクトリをホスト側に作成してコンテナ側と同期
    volumes: 
      - mysql_data:/var/lib/mysql/
    # .envの環境変数を展開してMYSQLコンテナのパスワードを登録
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
  
  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
    volumes:
      - ./backend:/$WORKDIR
      - bundle_data:/usr/local/bundle
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 8000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
    volumes:
      - ./frontend:/$WORKDIR
    ports:
      - 8080:8080
    depends_on:
      - backend
    command: sh -c "cd photo && yarn serve"

volumes:
  bundle_data:
  mysql_data:
